### ISSUE TITLE
和spark 3.2.0 及以上版本兼容问题

### ISSUE THREAD

**Issue by cocdkl** [apache/incubator-livy#406]
现在已经可以使用scala 2.12.15成功编译livy 0.8.0，但是在使用 spark3.2 及 3.3 以上版本时，pyspark 3.3 可以在yarn启动spark，但是提交不了任务，这是代码：
from pyspark.sql import SparkSession
spark=SparkSession.builder.appName("test").enableHiveSupport().getOrCreate()

spark.sql("show databases").show()
这是问题报错：
23/05/18 14:11:34 INFO BlockManagerMasterEndpoint: Registering block manager localhost:41641 with 366.3 MiB RAM, BlockManagerId(2, localhost, 41641, None)
23/05/18 14:11:34 INFO SparkEntries: Spark context finished initialization in 16437ms
23/05/18 14:11:34 INFO SparkEntries: Created Spark session.
23/05/18 14:11:41 ERROR PythonInterpreter: Process has died with 1
23/05/18 14:11:41 ERROR PythonInterpreter: Traceback (most recent call last):
  File "/tmp/6067082446938324509", line 722, in <module>
    sys.exit(main())
  File "/tmp/6067082446938324509", line 570, in main
    exec('from pyspark.sql import HiveContext', global_dict)
  File "<string>", line 1, in <module>
  File "/home/cocdkl/soft/spark-3.3.0-bin-hadoop3/python/lib/pyspark.zip/pyspark/__init__.py", line 71
    def since(version: Union[str, float]) -> Callable[[F], F]:
                     ^
SyntaxError: invalid syntax

通过hue提交的代码，希望得到解答

**Comment by cocdkl** [comment]
这是通过spark 3.2.4 提交任务报的错：
23/05/18 17:43:00 INFO SparkEntries: Created Spark session.
23/05/18 17:43:00 INFO BlockManagerMasterEndpoint: Registering block manager localhost:33381 with 912.3 MiB RAM, BlockManagerId(2, localhost, 33381, None)
23/05/18 17:43:25 ERROR PythonInterpreter: Process has died with 1
23/05/18 17:43:25 ERROR PythonInterpreter: Traceback (most recent call last):
  File "/tmp/8001765088071541442", line 722, in <module>
    sys.exit(main())
  File "/tmp/8001765088071541442", line 570, in main
    exec('from pyspark.sql import HiveContext', global_dict)
  File "<string>", line 1, in <module>
  File "/home/cocdkl/soft/spark-3.2.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/__init__.py", line 53, in <module>
  File "/home/cocdkl/soft/spark-3.2.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/rdd.py", line 34, in <module>
  File "/home/cocdkl/soft/spark-3.2.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/java_gateway.py", line 31, in <module>
  File "/home/cocdkl/soft/spark-3.2.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/find_spark_home.py", line 68
    print("Could not find valid SPARK_HOME while searching {0}".format(paths), file=sys.stderr)
                                                                                   ^
SyntaxError: invalid syntax



奇怪的是在yarn ，spark的集群是启动的，但是一提交具体代码作业，就会报错。

希望得到解决，谢谢

**Comment by yantzu** [comment]
We haven't tried Spark 3.3 yet, but Spark 3.2 should work. The log show
error happens in Spark's code /pyspark.zip/pyspark/find_spark_home.py which
seems not related to Livy, 2 suggestion:
1, set SPARK_HOME in livy, to avoid find spark home
2, check your python version

cocdkl ***@***.***> 于2023年5月18日周四 17:46写道：

**Comment by cocdkl** [comment]
感谢您抽出时间帮我解答问题
我在 livy-env.sh中进行了如下配置
SPARK_HOME=/home/cocdkl/soft/spark-3.2.4-bin-hadoop2.7
SPARK_CONF_DIR=/home/cocdkl/soft/spark-3.2.4-bin-hadoop2.7/conf

并且通过python -V 得到的版本为 2.7.16

我尝试过通过spar直接执行 pyspark命令，可以正常操作。

我写改过 /pyspark.zip/pyspark/find_spark_home.py 这个脚本，将这个脚本的返回值固化为我本地的spark_home目录，但是还是会报其他的错误。

**Comment by cocdkl** [comment]
这是我pom文件修改的地方
 <scala.binary.version>2.12</scala.binary.version>
 <scala.version>2.12.15</scala.version>
    
 <spark.version>3.2.4</spark.version>




 <groupId>net.alchim31.maven</groupId>
    <artifactId>scala-maven-plugin</artifactId>
    <version>4.8.1</version>

都是对相应的版本信息进行修改

**Comment by yantzu** [comment]
你设置了SPARK_HOME就不会执行find_spark_home.py了，所以可以工作，Spark3最好用python 3

cocdkl ***@***.***> 于2023年5月22日周一 08:51写道：

**Comment by cocdkl** [comment]
再次感谢您回答我的问题
以下是我环境变量的配置
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin
export JAVA_HOME=/home/cocdkl/soft/jdk1.8.0_371
export HADOOP_HOME=/home/cocdkl/soft/hadoop-3.3.0
export HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop
export HIVE_HOME=/home/cocdkl/soft/apache-hive-3.1.2-bin
export HIVE_CONF_DIR=/home/cocdkl/soft/apache-hive-3.1.2-bin/conf
#export HIVE_HOME=/home/cocdkl/soft/apache-hive-3.1.3-bin
#export HIVE_CONF_DIR=/home/cocdkl/soft/apache-hive-3.1.3-bin/conf
#export SPARK_HOME=/home/cocdkl/soft/spark-3.0.3-bin-hadoop3.2
#export SPARK_HOME=/home/cocdkl/soft/spark-3.3.0-bin-hadoop3
#export SPARK_HOME=/home/cocdkl/soft/spark-2.3.0-bin-hadoop2.7
export SPARK_HOME=/home/cocdkl/soft/spark-3.2.4-bin-hadoop2.7
#export SPARK_HOME=/home/cocdkl/soft/spark-2.4.8-bin-without-hadoop
export SCALA_HOME=/home/cocdkl/soft/scala-2.13.8
export HBASE_HOME=/home/cocdkl/soft/hbase-2.4.15
export ZOOKEEPER_HOME=/home/cocdkl/soft/apache-zookeeper-3.7.1-bin
export PATH=$JAVA_HOME/bin:$PATH
export PATH=$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$PATH
export PATH=$HIVE_HOME/bin:$PATH
export PATH=$SPARK_HOME/bin:$PATH
export PATH=$SCALA_HOME/bin:$PATH
export PATH=$HBASE_HOME/bin:$PATH
export PATH=$ZOOKEEPER_HOME/bin:$PATH
export CLASSPATH=''
export HADOOP_CLASSPATH=`hadoop classpath`
#export HADOOP_CLASSPATH=/home/cocdkl/soft/HADOOP_CLASSPATH/*

已经设置了SPARK_HOME，但是还是执行find_spark_home.py，这也是我奇怪的地方。

**Comment by cocdkl** [comment]
或者您有编译好的可以支持spark3.2的livy吗，可以提供一下或者更新一下官网下载包吗？我看官网还是0.7.1。

**Comment by yantzu** [comment]
对Spark3.2的支持我我们没改过代码，就是支持的。
你设置的环境变量里很多都是Livy不需要的吧，我不确定有没有影响，你可以本地debug一下livy，看看Livy里的Spark启动类（
*SparkProcessBuilder或者**ContextLaunche*r）在提交任务的时候环境变量对不对。

cocdkl ***@***.***> 于2023年5月29日周一 09:59写道：

**Comment by cocdkl** [comment]
首先感谢您的回答。
然后是通过源码查看还是在哪里配置debug选项？
最后，您说没有修改代码，那您的pom有修改吗？我看默认的pom是配置的是spark2.4.5和Scala2.11。您能否分享一下你那边支持spark3.2.0的pom文件？

**Comment by yantzu** [comment]
debug就是正常的java程序debug。
livy代码里对scala 2.11和scala2.12分别有支持，需要兼容的地方有两个maven模块

cocdkl ***@***.***> 于2023年6月4日周日 08:40写道：

**Comment by cocdkl** [comment]
抱歉，我还是没有解决，您是否能提供一下支持spark3.2.0的pom文件呢？

**Comment by cocdkl** [comment]
已经解决了，是python版本的问题，需要python3，但是我这边配置的是python2
